# Generated by Django 4.0.6 on 2022-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iyke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('projects', models.CharField(max_length=150, null=True)),
                ('pro_img', models.ImageField(default='blank', upload_to='images')),
            ],
        ),
    ]
